### PR TITLE
Publish: Thoughts on Training Runs

### PR DESCRIPTION
**Pull request by DanHeidinga**
Publish the writeup on training runs

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Mark Reinhold](https://openjdk.org/census#mr) (@mbreinhold - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/leyden-docs.git pull/3/head:pull/3` \
`$ git checkout pull/3`

Update a local copy of the PR: \
`$ git checkout pull/3` \
`$ git pull https://git.openjdk.org/leyden-docs.git pull/3/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3`

View PR using the GUI difftool: \
`$ git pr show -t 3`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/leyden-docs/pull/3.diff">https://git.openjdk.org/leyden-docs/pull/3.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/leyden-docs/pull/3#issuecomment-2334151967)

### CODE REVIEW

**Comment by mbreinhold** [comment]
Oops, it looks like you opened this PR and the other open PR against openjdk:master. I think you meant leyden-docs:master?

**Comment by DanHeidinga** [comment]
I think this might be a GitHub ui issue - the text says "merge 3 commits into `openjdk:master`" but when I hover on it, it actually links to https://github.com/openjdk/leyden-docs/tree/master

**Comment by mbreinhold** [comment]
> I think this might be a GitHub ui issue - the text says "merge 3 commits into `openjdk:master`" but when I hover on it, it actually links to https://github.com/openjdk/leyden-docs/tree/master

Well ... that’s awfully confusing!

**Review by mbreinhold — APPROVED** [review]

**Pull request closed without merging**
